// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwyjfbiehindtuwuvkto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eWpmYmllaGluZHR1d3V2a3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDI4NzIsImV4cCI6MjA3Mzc3ODg3Mn0.p00L5ChoTuHPXVDp7LN2MJJFX2WvYxr9tpd4EsoALtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});